package com.turnoverdoc.turnover.model;

public enum OrderStatus {
    RECEIVED,
    REQUEST_FOR_DOCS,
    ALL_DOCS_RECEIVED,
    REFUND_REQUEST_SENT_HMRC,
    TAX_RETURN_TO_HMRC,
    CHECK_RECEIVED,
    CHECK_BANKED,
    REQUEST_FOR_BANK_DETAILS,
    BANK_DETAILS_RECEIVED,
    TRANSFER_MADE
}
