package com.turnoverdoc.turnover.model;

public enum OrderStatus {
    RECEIVED,
    REQUEST_DOCUMENTS_IS_MADE,
    REQUEST_P45_P60_SENT_TO_EMPLOYER,
    P45_P60_RECEIVED_FROM_EMPLOYER,
    PACKAGE_DOCUMENTS_RECEIVED,
    REFUND_REQUEST_SENT_HMRC,
    REQUEST_ADDITIONAL_INFORMATION_INFO_RECEIVED_FROM_HMRC,
    ADDITIONAL_INFO_SENT_TO_HMRC,
    CHECK_RECEIVED,
    CHECK_CASHED,
    CUSTOMER_BANK_DETAILS_RECEIVED,
    FUNDS_SENT_TO_CLIENT
}
